# Generated by Django 4.2.2 on 2025-06-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_system', '0002_alter_accesslog_id_alter_address_id_alter_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='is_skip_profile',
            field=models.BooleanField(default=False, help_text='Whether user has skipped profile creation'),
        ),
    ]
