# Generated by Django 4.2.2 on 2025-06-15 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_system', '0006_company_cover_image_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completion_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('basic_info', 'Basic Information Completed'), ('family_info', 'Family Information Added'), ('address_info', 'Address Information Added'), ('education_info', 'Education Information Added'), ('employment_info', 'Employment Information Added'), ('completed', 'Profile Completed')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='Whether profile is in draft mode'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_step_completed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Verification Pending'), ('verified', 'Verified'), ('rejected', 'Verification Rejected')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='govt_id_scan',
            field=models.FileField(blank=True, null=True, upload_to='id_scans/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
